import { Download } from "lucide-react";
import { cn } from "@/lib/utils";

type Message = { role: "user" | "assistant"; content: string };

type Segment =
  | { type: "text"; lines: string[] }
  | { type: "options"; options: { key: string; label: string }[] };

function parseSegments(text: string): Segment[] {
  const lines = text.split("\n");
  const segments: Segment[] = [];
  let textLines: string[] = [];
  let optionLines: { key: string; label: string }[] = [];

  for (const line of lines) {
    const optMatch = line.match(/^([A-E])\)\s+(.+)/);
    if (optMatch) {
      if (textLines.length) {
        segments.push({ type: "text", lines: textLines });
        textLines = [];
      }
      optionLines.push({ key: optMatch[1], label: optMatch[2] });
    } else {
      if (optionLines.length) {
        segments.push({ type: "options", options: optionLines });
        optionLines = [];
      }
      textLines.push(line);
    }
  }
  if (textLines.length) segments.push({ type: "text", lines: textLines });
  if (optionLines.length) segments.push({ type: "options", options: optionLines });
  return segments;
}

function renderInline(text: string) {
  return text.split(/(\*\*[^*]+\*\*)/g).map((part, i) =>
    part.startsWith("**") && part.endsWith("**")
      ? <strong key={i}>{part.slice(2, -2)}</strong>
      : part
  );
}

function renderTextLine(line: string, i: number) {
  if (line.startsWith("### ")) return <h3 key={i} className="mt-4 mb-1 font-semibold text-sm">{line.slice(4)}</h3>;
  if (line.startsWith("## ")) return <h2 key={i} className="mt-5 mb-1 font-semibold">{line.slice(3)}</h2>;
  if (line.startsWith("- ") || line.startsWith("• ")) return <li key={i} className="ml-4 list-disc text-sm leading-relaxed">{renderInline(line.slice(2))}</li>;
  if (line === "") return <div key={i} className="h-2" />;
  return <p key={i} className="text-sm leading-relaxed">{renderInline(line)}</p>;
}

export function MessageBubble({
  message,
  isLast,
  onOptionSelect,
  generatedImage,
  imageLoading,
}: {
  message: Message;
  isLast?: boolean;
  onOptionSelect?: (value: string) => void;
  generatedImage?: string;
  imageLoading?: boolean;
}) {
  if (message.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="max-w-[70%] rounded-2xl rounded-tr-sm bg-primary/10 px-4 py-3 text-sm text-foreground">
          {message.content}
        </div>
      </div>
    );
  }

  // Strip the [[GENERATE_IMAGE:...]] marker from rendered content
  const displayContent = message.content.replace(/\[\[GENERATE_IMAGE:[\s\S]*?\]\]/g, "").trim();
  const segments = parseSegments(displayContent);

  return (
    <div className="flex gap-3">
      <div className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-primary text-[10px] font-bold text-white">
        A
      </div>
      <div className="flex-1 space-y-3 pt-0.5">
        {/* Generated image */}
        {imageLoading && (
          <div className="flex items-center gap-2 rounded-xl border border-border bg-muted/40 px-4 py-3">
            <div className="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            <span className="text-sm text-muted-foreground">Generating image…</span>
          </div>
        )}
        {generatedImage && (
          <div className="overflow-hidden rounded-xl border border-border bg-white shadow-sm">
            <img src={generatedImage} alt="Generated by Agni" className="w-full" />
            <div className="flex items-center justify-between border-t border-border px-4 py-2.5">
              <span className="text-xs text-muted-foreground">Generated with DALL·E 3</span>
              <a
                href={generatedImage}
                download="sarvast-image.png"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1.5 text-xs font-medium text-primary hover:underline"
              >
                <Download className="h-3.5 w-3.5" />
                Download
              </a>
            </div>
          </div>
        )}

        {segments.map((seg, si) => {
          if (seg.type === "text") {
            return (
              <div key={si} className="space-y-0.5">
                {seg.lines.map((line, li) => renderTextLine(line, li))}
              </div>
            );
          }
          return (
            <div key={si} className="flex flex-wrap gap-2 pt-1">
              {seg.options.map((opt) => (
                <button
                  key={opt.key}
                  onClick={() => onOptionSelect?.(`${opt.key}) ${opt.label}`)}
                  disabled={!isLast || !onOptionSelect}
                  className={cn(
                    "flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm transition-all",
                    isLast && onOptionSelect
                      ? "border-border bg-white text-foreground shadow-sm hover:border-primary/40 hover:bg-primary/5 hover:text-primary hover:shadow-md cursor-pointer"
                      : "border-border bg-white/50 text-muted-foreground cursor-default"
                  )}
                >
                  <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-muted text-[10px] font-semibold text-muted-foreground">
                    {opt.key}
                  </span>
                  {opt.label}
                </button>
              ))}
            </div>
          );
        })}
      </div>
    </div>
  );
}
