"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Loader2, Sparkles, RefreshCw } from "lucide-react";
import { cn } from "@/lib/utils";

type Action = {
  priority: 1 | 2 | 3;
  agent: string;
  title: string;
  description: string;
  href: string;
};

const AGENT_COLORS: Record<string, string> = {
  guru: "bg-blue-100 text-blue-700",
  karma: "bg-green-100 text-green-700",
  mitra: "bg-yellow-100 text-yellow-700",
  narad: "bg-pink-100 text-pink-700",
  chitra: "bg-purple-100 text-purple-700",
  vani: "bg-indigo-100 text-indigo-700",
  vyas: "bg-teal-100 text-teal-700",
  para: "bg-red-100 text-red-700",
};

const PRIORITY_CONFIG = {
  1: { label: "P1", color: "bg-red-500 text-white", border: "border-red-200" },
  2: { label: "P2", color: "bg-orange-400 text-white", border: "border-orange-200" },
  3: { label: "P3", color: "bg-muted text-muted-foreground", border: "border-border" },
};

export function ActionItems() {
  const [actions, setActions] = useState<Action[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = async (refresh = false) => {
    if (refresh) setRefreshing(true);
    else setLoading(true);
    try {
      const res = await fetch("/api/agents/chitra/actions");
      const data = await res.json();
      setActions(data.actions ?? []);
    } catch {
      setActions([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => { load(); }, []);

  return (
    <div className="flex h-full flex-col rounded-2xl border border-border bg-card shadow-sm">
      <div className="flex items-center justify-between border-b border-border px-5 py-4">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-orange-500" />
          <h2 className="text-sm font-semibold">Action Items</h2>
        </div>
        <button
          onClick={() => load(true)}
          disabled={refreshing}
          className="text-muted-foreground transition-colors hover:text-foreground"
          title="Refresh"
        >
          <RefreshCw className={cn("h-3.5 w-3.5", refreshing && "animate-spin")} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto">
        {loading ? (
          <div className="flex h-40 items-center justify-center gap-2 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            Analysing your marketing…
          </div>
        ) : actions.length === 0 ? (
          <div className="flex h-40 items-center justify-center text-sm text-muted-foreground">
            No actions available yet.
          </div>
        ) : (
          <div className="divide-y divide-border">
            {actions
              .sort((a, b) => a.priority - b.priority)
              .map((action, i) => {
                const p = PRIORITY_CONFIG[action.priority] ?? PRIORITY_CONFIG[3];
                const agentColor = AGENT_COLORS[action.agent.toLowerCase()] ?? "bg-muted text-muted-foreground";
                return (
                  <Link
                    key={i}
                    href={action.href}
                    className={cn(
                      "group flex flex-col gap-2 px-5 py-4 transition-colors hover:bg-muted/30",
                    )}
                  >
                    <div className="flex items-center gap-2">
                      <span className={cn("rounded px-1.5 py-0.5 text-[10px] font-bold", p.color)}>
                        {p.label}
                      </span>
                      <span className={cn("rounded-full px-2 py-0.5 text-[10px] font-medium capitalize", agentColor)}>
                        {action.agent}
                      </span>
                      <ArrowRight className="ml-auto h-3.5 w-3.5 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" />
                    </div>
                    <p className="text-sm font-medium leading-tight">{action.title}</p>
                    <p className="text-xs leading-relaxed text-muted-foreground">{action.description}</p>
                  </Link>
                );
              })}
          </div>
        )}
      </div>

      <div className="border-t border-border px-5 py-3">
        <p className="text-[10px] text-muted-foreground/60">
          Generated by Chitra · refreshes with new data
        </p>
      </div>
    </div>
  );
}
